<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPaUKWdD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPaUKWdD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPaUKWdD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPaUKWdD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPaUKWdD\App_KernelDevDebugContainer([
    'container.build_hash' => 'PaUKWdD',
    'container.build_id' => '1ac15ac5',
    'container.build_time' => 1575485775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPaUKWdD');
