<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF0uYiq9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF0uYiq9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF0uYiq9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF0uYiq9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF0uYiq9\App_KernelDevDebugContainer([
    'container.build_hash' => 'F0uYiq9',
    'container.build_id' => '6f4221e3',
    'container.build_time' => 1575541202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF0uYiq9');
